### ISSUE TITLE
How to run (unit) tests for the frontend?

### ISSUE THREAD

**Issue by tssmits** [flamingo-geocms/flamingo#1448]
First of all, hello :) This is my first post here!

Afaik there is no feature yet in Flamingo that allows the user to select multiple features at the same time, and edit their features in bulk.

I'm currently working on implementing this. My approach is to add a new component to the javascript frontend of the viewer. I'm basing it on the [`Edit.js`](https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/components/Edit.js) component.

My question is, how do I test the frontend? Are there unit tests / integration tests that deal with the javascript? Is there a maven command that I can run?

**Comment by mprins** [comment]
> Afaik there is no feature yet in Flamingo that allows the user to select multiple features at the same time, and edit their features in bulk.

there is some multi-feature select like function in spatial filter, after setting a spatial filter it will update the attribute list component with "selected" features, "simple" filters doe similar things but are (imo) a pain to understand due to lots of subclassing etc.

> I'm currently working on implementing this. My approach is to add a new component to the javascript frontend of the viewer. I'm basing it on the Edit.js component.

Current editing is indeed limited to one feature only, so yes probably subclassing the current Edit component will get you started.
You probably also need to add a new Resolution to the EditFeatureActionBean so it will handle multiple features at a time and the bulk edit can be done in a single transaction, maybe you can just send something like an arrays of FIDs and a filter expression to the backend.

I'm not sure if you want to just set same the attribute value of a set of features, or if you want to set different attribute values. eg. set all feature['some attribute']'s to the same value or set different values for different features

> My question is, how do I test the frontend? Are there unit tests / integration tests that deal with the javascript? Is there a maven command that I can run?

there is no frontend testing code, it would probably require setting up things like Selenium or other similar, most code won't work without a DOM I think.
