### ISSUE TITLE
Use selected layer from TOC to automatically select Layer in AttributeList

### ISSUE THREAD

**Issue by geertplaisier** [flamingo-geocms/flamingo#375]
Currently you always have to select a layer in the AttributeList component. This should be changed so that the first selected layer from the TOC is already preselected.

**Comment by mprins** [comment]
:bomb: this fix causes a problem in the Edit, SpatialFilter (and Split + Merge) controls because calling `.setValue(selectedLayer, true);` on the LayerSelector
fires the ON_LAYERSELECTOR_CHANGE event, this is used to clear the drawing layer of those controls, but this is not initialized until the control is used/openend.

eg. [Edit.js#257](https://github.com/flamingo-geocms/flamingo/blob/master/viewer/src/main/webapp/viewer-html/components/Edit.js#L257) 
```javascript
    layerChanged: function (appLayer, afterLoadAttributes, scope) {
        if (appLayer != null) {
// Null pointer on this.vectorLayer
            this.vectorLayer.removeAllFeatures();
            this.mode = null;
```
