### ISSUE TITLE
Disable autocomplete for username/password fields

### ISSUE THREAD

**Issue by matthijsln** [flamingo-geocms/flamingo#507]
In service details username/password fields are autocompleted with the Flamingo user account details, this is annoying. Rename fields or check if autocomplete="off" works. Also check in other places such as user management

**Comment by mprins** [comment]
I had a try at this a while ago, but the stripes taglib we are using atm turned out not to support this attribute on input or form elements, there is a new release of stripes that may work, but still you may still run into this issue: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

**Comment by matthijsln** [comment]
we can use custom attributes with stripes-dynattr taglibs

**Comment by mprins** [comment]
closed with #513
