### ISSUE TITLE
Cyclorama function does not work anymore

### ISSUE THREAD

**Issue by andreweijmer** [flamingo-geocms/flamingo#646]
### Where?
viewer-admin/bronnen/cyclorama
### What happened
Tried to add a new pfx-file. Could select the pfx-file but could not fill in the required username and password.

### What did you expect?
fields to fill in username and password

### Version
4.7.1
### URL
no acces (only on reply)

**Comment by mprins** [comment]
4.7.2 was never released. Which is the actual version?

**Comment by mprins** [comment]
It seems this was introduced in #513 which is part of v 4.7.0, any version before that should be OK

**Comment by andreweijmer** [comment]
Does that mean that this functionality is not available anymore?

**Comment by mprins** [comment]
No; it will be/is fixed in the next release (4.7.5); something went wrong when we tried to prevent automatic password filling of password fields; this page used alternate syntax to include something so it was missing a library to render a dynamic tag for username and password.

If you need this now you can download the jar files and replace the [`cyclorama.jsp`](https://github.com/flamingo-geocms/flamingo/blob/master/viewer-admin/src/main/webapp/WEB-INF/jsp/services/cyclorama.jsp) in the viewer-admin .war and deploy the app, or replace the file in a deployed instance.

The exact path is: `WEB-INF/jsp/services/cyclorama.jsp` in `viewer-admin` (download from: https://raw.githubusercontent.com/flamingo-geocms/flamingo/master/viewer-admin/src/main/webapp/WEB-INF/jsp/services/cyclorama.jsp)

**Comment by andreweijmer** [comment]
thanks!
