### ISSUE TITLE
Zoom to object in attributenlijst doesn't zoom to object

### ISSUE THREAD

**Issue by KJLammers** [flamingo-geocms/flamingo#742]
### Version
Viewer 4.7.10-rc2, 5.0.0-beta3

### Browser info
Chrome 55.0.2883.87
Firefox 50.1.0

### URL
http://flamingo4.b3p.nl/viewer/app/BAG%20(Testomgeving)/v1#

### Where?
Viewer -> Attributenlijst,

### What happened
After configuring the attributenlijst to show a zoom to attribute button a magnifying glass will appear before each row in the attributenlijst component in a viewer. Clicking this should result in zooming in to the object. The actual result however, is that the map zooms in to either the utmost left-bottom corner or right-upper corner of the map. 

### What did you expect?
Clicking the magnifying glass should make the viewer zoom in to the object the magnifying glass 'belongs to'. 

### Reproduce

  1. Open http://flamingo4.b3p.nl/viewer/app/BAG%20(Testomgeving)/v1
  2. Activate any layer
3. Activate attributenlijst
4. click on one of the magnifying glasses of the objects in the attributenlijst
5. let the viewer zoom in
  

### Server log
There is no logging of this problem

**Comment by mprins** [comment]
I think the view does not expose a persistent primary key (so no reliable FID) so the filtering fails because it depends on a consistent FID/PK being present.
eg. looking at "Verblijfsobjecten" and clicking the first record in the table (Abel Tasmanlaan 106) a few times results in different requested feature id's for each request while these should be the same each time.

request:
```
buffer:10
filter:IN ('v_verblijfsobject_vbo_pand.fid-5b9cdcf6_1594b2a425f_-65ee')
appLayer:547
```

response: 
```json
{"extent":{"miny":-16,"minx":-16,"maxy":15,"maxx":15},"success":true}
```

other requests (filter part):
filter:IN ('v_verblijfsobject_vbo_pand.fid-5b9cdcf6_1594b2a425f_-65bb')
filter:IN ('v_verblijfsobject_vbo_pand.fid-5b9cdcf6_1594b2a425f_-6589')

as you can see the FID is different each time; where it should be exactly the same.
The response is the same each time, but is bogus as it is basically the bounding box of the "buffer" param in the request.

This should be solved in the database by adding a geotools primary key table; some examples are available in the BRMO eg. https://github.com/B3Partners/brmo/blob/master/datamodel/utility_scripts/oracle/403_create_geotools_primarykey_metatable.sql 

I'm assuming the view has a suitable PK column otherwise you will need to generate one eg. using row number
